name: lob_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  riverpod_annotation: ^2.3.5
  collection: ^1.16.0
  firebase_messaging: ^14.9.4
  http: ^1.2.1
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  melos: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/pics/LOB_Logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/pics/google.png
    - lib/pics/LOB_Logo.png
  fonts:
  - family: Proxima
    fonts: 
      - asset: fonts/Proxima.ttf


