// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2WybU-m1Oq9gNB7YpkNjOI2t3Cg5znA',
    appId: '1:286786402274:web:2718f7e16ae9989e74abbb',
    messagingSenderId: '286786402274',
    projectId: 'lobapp-bf259',
    authDomain: 'lobapp-bf259.firebaseapp.com',
    storageBucket: 'lobapp-bf259.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJKeUMTkl2-iYhuy7k0z2nyB25lQbfE0k',
    appId: '1:286786402274:android:39e82ea6da3552c474abbb',
    messagingSenderId: '286786402274',
    projectId: 'lobapp-bf259',
    storageBucket: 'lobapp-bf259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItkOPA_3uJ5Lfd8irTmk5Z0iQ17B1l2c',
    appId: '1:286786402274:ios:c17a02edb75511c074abbb',
    messagingSenderId: '286786402274',
    projectId: 'lobapp-bf259',
    storageBucket: 'lobapp-bf259.appspot.com',
    iosBundleId: 'com.example.lobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDItkOPA_3uJ5Lfd8irTmk5Z0iQ17B1l2c',
    appId: '1:286786402274:ios:c17a02edb75511c074abbb',
    messagingSenderId: '286786402274',
    projectId: 'lobapp-bf259',
    storageBucket: 'lobapp-bf259.appspot.com',
    iosBundleId: 'com.example.lobApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi2WybU-m1Oq9gNB7YpkNjOI2t3Cg5znA',
    appId: '1:286786402274:web:4ce63f753cfec08c74abbb',
    messagingSenderId: '286786402274',
    projectId: 'lobapp-bf259',
    authDomain: 'lobapp-bf259.firebaseapp.com',
    storageBucket: 'lobapp-bf259.appspot.com',
  );
}
